name: 🚀 Feature Development
description: Plan and track feature development
title: "[FEATURE] "
labels: ["feature", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Development
        Use this template for new features and enhancements.
        
  - type: input
    id: feature-name
    attributes:
      label: "Feature Name"
      description: "Clear, descriptive name for the feature"
    validations:
      required: true
      
  - type: textarea
    id: business-outcome
    attributes:
      label: "Business Outcome"
      description: "What business problem does this solve?"
      placeholder: "This feature will enable... which results in..."
    validations:
      required: true
      
  - type: textarea
    id: user-impact
    attributes:
      label: "User Impact"
      description: "How will users benefit?"
      placeholder: "Users will be able to... which saves them..."
    validations:
      required: true
      
  - type: textarea
    id: technical-approach
    attributes:
      label: "Technical Approach"
      description: "High-level technical solution"
      placeholder: "We will implement... using... to achieve..."
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      description: "Definition of done"
      placeholder: |
        - [ ] Core functionality works as specified
        - [ ] Security requirements met
        - [ ] Performance benchmarks achieved
        - [ ] Documentation complete
        - [ ] Tests pass
    validations:
      required: true
      
  - type: textarea
    id: ai-integration
    attributes:
      label: "AI Enhancement Opportunities"
      description: "How can AI improve this feature?"
      placeholder: "Consider: automation, intelligence, prediction, optimization..."
      
  - type: dropdown
    id: complexity
    attributes:
      label: "Complexity Level"
      options:
        - "🟢 Simple (1-2 days)"
        - "🟡 Medium (3-5 days)"
        - "🟠 Complex (1-2 weeks)"
        - "🔴 Epic (2+ weeks)"
    validations:
      required: true
      
  - type: dropdown
    id: ai-dependency
    attributes:
      label: "AI/ML Dependency"
      options:
        - "None - Traditional development"
        - "Low - Basic AI integration"
        - "Medium - Significant AI component"
        - "High - AI-first feature"
    validations:
      required: true
