# File: .github/workflows/contract-specific.yml
# Enhanced automation for core-contracts repository

name: Core Contracts Automation
on:
  issues:
    types: [opened, labeled, edited]

jobs:
  contract-opportunity-analysis:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'ProgrediSystems/core-contracts' && (
        contains(github.event.issue.labels.*.name, 'contract-opportunity') ||
        contains(github.event.issue.title, 'contract') ||
        contains(github.event.issue.title, 'RFP') ||
        contains(github.event.issue.title, 'proposal')
      )
    steps:
      - name: Enhanced Contract Analysis
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const title = issue.title;
            const body = issue.body || '';
            
            // Extract contract details
            const contractNumber = title.match(/([A-Z0-9-]+(?:RFP|SOL|Contract|Award)[A-Z0-9-]*)/i)?.[1] || 'TBD';
            const value = title.match(/\$([0-9,]+(?:\.[0-9]{2})?[KMB]?)/)?.[1] || body.match(/\$([0-9,]+(?:\.[0-9]{2})?[KMB]?)/)?.[1] || 'TBD';
            const agency = title.match(/(Army|Navy|Air Force|Marines|DHS|DOD|Defense|Federal)/i)?.[1] || 'TBD';
            const deadline = body.match(/deadline[:\s]*([0-9]{4}-[0-9]{2}-[0-9]{2}|[0-9]{1,2}\/[0-9]{1,2}\/[0-9]{4})/i)?.[1] || 'TBD';
            
            // Calculate PWin based on contract characteristics
            let pwin = 50; // Default
            if (title.toLowerCase().includes('sole source')) pwin = 85;
            else if (title.toLowerCase().includes('limited competition')) pwin = 65;
            else if (title.toLowerCase().includes('small business')) pwin = 70;
            else if (title.toLowerCase().includes('incumbent')) pwin = 75;
            
            const comment = `## 🏛️ Government Contract Analysis
            
            **Contract Number**: ${contractNumber}
            **Estimated Value**: $${value}
            **Agency**: ${agency}
            **Proposal Deadline**: ${deadline}
            **Initial PWin Estimate**: ${pwin}%
            
            ### 🎯 Project Board Status:
            ✅ **Added to Revenue Pipeline** (#4) → 💡 Opportunities
            ✅ **Added to Defense Market Focus** (#6) → 🏛️ Contract Opportunities
            
            ### 📋 Contract Pursuit Checklist:
            
            #### Phase 1: Opportunity Assessment (Week 1)
            - [ ] **RFP Analysis**: Download and review full RFP
            - [ ] **Requirements Mapping**: Map requirements to capabilities
            - [ ] **Competitive Analysis**: Identify likely competitors
            - [ ] **Teaming Strategy**: Determine prime vs. sub approach
            - [ ] **Go/No-Go Decision**: Complete bid decision matrix
            
            #### Phase 2: Proposal Development (Week 2-3)
            - [ ] **Technical Approach**: Develop solution architecture
            - [ ] **Past Performance**: Gather relevant project examples
            - [ ] **Team Assembly**: Identify key personnel
            - [ ] **Cost Modeling**: Develop pricing strategy
            - [ ] **Compliance Review**: Ensure all requirements met
            
            #### Phase 3: Submission & Follow-up (Week 4+)
            - [ ] **Final Review**: Quality assurance check
            - [ ] **Submission**: Submit via required portal
            - [ ] **Q&A Period**: Respond to government questions
            - [ ] **Orals Prep**: Prepare for potential presentations
            
            ### 🔗 Useful Links:
            - [Revenue Pipeline](https://github.com/orgs/ProgrediSystems/projects/4)
            - [Defense Market Focus](https://github.com/orgs/ProgrediSystems/projects/6)
            - [Contract Opportunities View](https://github.com/orgs/ProgrediSystems/projects/6?filterQuery=label%3Acontract-opportunity)
            
            ### 🎮 Board Movement Guide:
            1. **Current**: 💡 Opportunities (newly identified)
            2. **Next**: 📋 Qualifying (after initial analysis)
            3. **Then**: 🎯 This Quarter (if Go decision made)
            4. **Finally**: 🔄 In Progress (during proposal writing)
            
            ---
            *🤖 Generated by ProgrediSystems Contract Intelligence System*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
