---
name: "Security Scan"
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
    
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Security scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      - name: Dependency review
        uses: actions/dependency-review-action@v3
        
      - name: SAST Scan
        uses: github/codeql-action/analyze@v2
        with:
          languages: javascript, python
---
