# File: .github/workflows/setup-labels.yml  
# Run this once to create standard labels across repositories

name: Setup ProgrediSystems Standard Labels
on:
  workflow_dispatch:  # Run manually
  repository_dispatch:
    types: [setup-labels]

jobs:
  create-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Create ProgrediSystems Standard Labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = [
              // Revenue Labels (Green family)
              { name: 'revenue-opportunity', color: '22c55e', description: '💰 Potential revenue generating opportunity' },
              { name: 'contract-opportunity', color: '16a34a', description: '🏛️ Government contract opportunity' },
              { name: 'client-opportunity', color: '65a30d', description: '🤝 Commercial client opportunity' },
              { name: 'cost-reduction', color: '84cc16', description: '💵 Reduces operational costs' },
              
              // Development Labels (Blue family)
              { name: 'feature', color: '3b82f6', description: '🚀 New feature development' },
              { name: 'enhancement', color: '6366f1', description: '⚡ Improve existing functionality' },
              { name: 'ai-enhancement', color: '8b5cf6', description: '🤖 AI/ML enhancement opportunity' },
              { name: 'bug', color: 'ef4444', description: '🐛 Bug fix required' },
              
              // Defense/Government Labels (Purple family)
              { name: 'government-rfp', color: '7c3aed', description: '🏛️ Government RFP or contract' },
              { name: 'cmmc', color: '6d28d9', description: '🛡️ CMMC compliance related' },
              { name: 'defense-contract', color: '5b21b6', description: '⚔️ Defense/military contract' },
              { name: 'compliance', color: '4c1d95', description: '📋 Compliance or certification' },
              
              // Priority Labels (Traffic light colors)
              { name: 'priority-critical', color: 'dc2626', description: '🔴 Critical priority - revenue/business impact' },
              { name: 'priority-high', color: 'ea580c', description: '🟠 High priority' },
              { name: 'priority-medium', color: 'ca8a04', description: '🟡 Medium priority' },
              { name: 'priority-low', color: '16a34a', description: '🟢 Low priority' },
              
              // Process Labels (Gray family)
              { name: 'needs-triage', color: '6b7280', description: '🔍 Needs initial review and prioritization' },
              { name: 'blocked', color: '374151', description: '🚫 Blocked by external dependency' },
              { name: 'in-review', color: '4b5563', description: '👀 Under review' },
              { name: 'sprint-ready', color: '059669', description: '✅ Ready for sprint inclusion' }
            ];

            let created = 0;
            let existing = 0;
            
            for (const label of labels) {
              try {
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ...label
                });
                console.log(`✅ Created label: ${label.name}`);
                created++;
              } catch (error) {
                if (error.status === 422) {
                  console.log(`ℹ️ Label ${label.name} already exists`);
                  existing++;
                } else {
                  console.error(`❌ Error creating label ${label.name}:`, error.message);
                }
              }
            }
            
            console.log(`\n📊 Summary: ${created} labels created, ${existing} already existed`);
