name: Validate Repository Structure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate JSON files
        run: |
          for file in $(find . -name "*.json"); do
            echo "Validating $file"
            cat $file | jq empty || echo "Error in $file"
          done
          
      - name: Generate repository summary
        run: |
          echo "# Repository Structure Report" > report.md
          echo "Generated on $(date)" >> report.md
          echo "## Directory Structure" >> report.md
          find . -type d -not -path "*/\.*" | sort | sed 's/^/- /' >> report.md
          
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: repository-report
          path: report.md
