name: Setup Labels
on:
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh label create "revenue-opportunity" --color "22c55e" --description "Revenue opportunity" --force
          gh label create "feature" --color "3b82f6" --description "New feature" --force  
          gh label create "government-rfp" --color "7c3aed" --description "Government RFP" --force
          echo "Labels created!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
